Feature
che30/TodoList pull request #1
Opened 2021-03-18 19:53 UTC by che30

In this project I carried out the following: 
- A class was created for a project 
- A class for a task to be added
- A class for the user interface
- Methods for functionality to add a project, add a task  delete a project and task were added
- Linters was set up
Any feedback and proposition is highly welcomed

2021-03-18 20:40 UTC, teekaytech requested changes
### Status: Invalid Code Review Request :x: 

__Hi @che30, I commend you for the great effort put into this project. However, I have to mark the project as invalid due to the following reason(s):__

- [ ] Your GitHub Action checks are not running. For your project to be considered for review, you must ensure that all GitHub Action checks are running successfully with no errors.

_**This submission will be marked as invalid. Kindly ensure you have running and passing GitHub Action checks before you submit another review request.**_



* * *

**_You can reach out to me on Twitter (@ola_lere), Github(@teekaytech), or slack (@taofeekolalere )_**

Happy Coding :man_technologist:

2021-03-18 22:36 UTC, christianotieno requested changes
Carried out mandatory changes as requested by TSE

2021-03-18 22:36 UTC, christianotieno commented on README.md
> +![screenshot](./dist/assets/images/todoshotOne.png)
## Improve the screenshot.
- As part of having and maintaining a professional repo, the README, being the gateway to the project ought to stand out at all time as it is what sells the project the most. 
- [ ] Please ensure that the screenshot is showing here as expected.

2021-03-18 22:36 UTC, christianotieno commented on README.md
> +- Use any browser of your choice, copy the absolute path of the  `index.html` and type in the search bar
## Improve the instructions of cloning and running the app locally.
- As part of having and maintaining a professional repo, the README, being the gateway to the project ought to stand out at all time as it is what sells the project the most.
- [x] Do you mind adding more instructions for running the code locally using webpack and the set scripts, in addition to the cloning instructions?

2021-03-18 22:36 UTC, christianotieno commented on README.md
> +- Twitter:[che55085128](https://twitter.com/che55085128)
```suggestion
- GitHub: [@che30](https://github.com/che30)
- LinkedIn: [Che Blanchard](https://www.linkedin.com/in/che-nsoh-9455271b0/)
- Twitter: [@che55085128](https://twitter.com/che55085128)
```

2021-03-18 22:36 UTC, christianotieno commented on README.md
> +This project is [MIT](./LICENSE.txt) licensed.
## Fix or remove dead links.
- [ ] the license link is currently a dead link, please fix this by either adding a working link to the project's licence or remove the link for a much cleaner README, thank you.

2021-03-18 22:36 UTC, christianotieno commented on dist/assets/stylesheets/main.css
> +  background-color: rgba(0,0,0,0.4); /* Black w/ opacity */
## Aim to remain `DRY`
- Though having comments on what the code is doing is highly encouraged. it is also encouraged to aim at `self-documenting` code> Thereby it relieves you the burden of getting to write unnecessary comments.   
- [ ] In this instance having these comments here feel like you are repeating yourself as the comments are doing exactly what the code demonstrates. I urge we resume most of them to have a cleaner codebase. Like so 👇🏾 
```suggestion
  display: none; 
  position: fixed; 
  z-index: 1; 
  padding-top: 50px; 
  left: 0;
  top: 0;
  width: 100%; 
  height: 100%; 
  overflow: auto;
  background-color: rgb(0,0,0); 
  background-color: rgba(0,0,0,0.4); 
```

2021-03-18 22:36 UTC, christianotieno commented on dist/assets/stylesheets/main.css
> +} */
## Avoid committing and pushing commented out code.
- [ ] It’s better to delete **commented piece of codes**. If you need to review a previous version of your code, use `git history` instead. More on this on this [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/no_inline_comments.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/).

2021-03-18 22:36 UTC, christianotieno commented on src/Task.js
> +//  localStorage.clear()
## Avoid committing and pushing commented out code.
- [ ] It’s better to delete **commented piece of codes**. If you need to review a previous version of your code, use `git history` instead. More on this on this [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/no_inline_comments.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/).

2021-03-18 22:36 UTC, christianotieno commented on src/index.js
> +
## Optional change
- [ ] can we have a scenario where after creating a project or a todo, the forms get removed on save without the user needing to reload the page? The problem appears to be there when moving from project to project; the user gets forced to reload the page to previously created todos. Do you mind fixing this?
- [ ] Also can we have the error message actually showing on the form fields when the user attempts to submit a half-filled form? Currently, the rules have been enforced but the user cant sees them on the page.

2021-03-18 22:36 UTC, christianotieno commented on src/index.js
> +//  UI.renderDefault();
## Avoid committing and pushing commented out code.
- [ ] It’s better to delete **commented piece of codes**. If you need to review a previous version of your code, use `git history` instead. More on this on this [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/no_inline_comments.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/).

2021-03-19 03:19 UTC, voscarmv requested changes
# Impressive work. 💻 👀 ✨ 
- Good work applying the changes requested by the previous code reviewer.
## However, there are some changes required 👀 🧰 🔨 🔧 
- When I add new ToDos to the default project, and then I click on the `default` project link, some ToDos are unintenionally deleted. Please fix this bug.
- When I add new Projects after and add some ToDos to the `default` as well as to the new project, my ToDos get deleted for no reason when I switch between different projects by clicking on their links. Please fix this as well.
- The ToDos are not displaying their priority level. Please show the priority level and also display it on the Edit form.
### Submit these changes and request a new code review! 😄 👍 

### Questions or comments? Reach me on [Twitter](https://twitter.com/voscarmv) or [LinkedIn](https://linkedin.com/in/oscar-mier) 🧑‍💻🗨️🧑‍💻 
# Happy Hacking! 🧠 ⌨️ 🖱️ 🖥️

2021-03-20 11:38 UTC, Forison requested changes
# Status::Approved✔️

#### You have done a good job on this one so far, all the issues raised in the last review have been addressed😶.

* [ ]  Currently, todo gets deleted after I update, let address this issue.
* [ ] Check other changes to be effected below👇

#### That is it, kindly make the changes and submit a re-review💪

#### Happy coding👨‍💻

Addo Forison

2021-03-20 11:38 UTC, Forison commented on dist/assets/stylesheets/main.css
> +  /* margin-left: 30%; */
* [ ] Remove commented code

2021-03-20 11:38 UTC, Forison commented on src/UI.js
> +  //  static setSelected(){
* [ ]  Remove commented code

2021-03-20 11:38 UTC, Forison commented on src/UI.js
> +  //  static getTargettedElement(){
* [ ]  Remove commented code

2021-03-20 11:38 UTC, Forison commented on src/index.js
> +  // const selectedId = JSON.parse(localStorage.getItem('selectedId'));
* [ ]  Remove commented code

2021-03-20 11:38 UTC, Forison commented on src/index.js
> +      // const selectedId = JSON.parse(localStorage.getItem('selectedId'));
* [ ]  Remove commented code

2021-03-20 11:38 UTC, Forison commented on src/index.js
> +  // const selectedId = JSON.parse(localStorage.getItem('selectedId'));
* [ ]  Remove commented code

2021-03-20 11:38 UTC, Forison commented on src/index.js
> +//  const selectedId = UI.getSelected()
* [ ]  Remove commented code

2021-03-20 12:15 UTC, che30 commented
Can't seem to find any commented code again sir

2021-03-20 12:35 UTC, christianotieno approved these changes
## Project Approved ♻️ 
Hello @che30 👋🏾 
Good job working on the changes. This project is now approved. 🥇 
### Happy coding 💻 
#### Christian Otieno (CR)

2021-03-20 12:37 UTC, merged